### ISSUE TITLE
doesn't work with private npm packages

### ISSUE THREAD

**Issue by vasco3** [mwilliamson/node-license-sniffer#4]

**Comment by mwilliamson** [comment]
I can't say that I have any experience with private npm packages. Do you know what's different about them that causes the issue?

**Comment by vasco3** [comment]
It throws an error 

I'm not sure what causes it. Looks like it crashes since private modules have nested package.jsons

```
$ node-license-sniffer --recurse

{ [Error: ENOENT, open 'node_modules/@my_private_modules/package.json']
  errno: -2,
  code: 'ENOENT',
  path: 'node_modules/@my_private_modules/package.json' }
```

**Comment by jokeyrhyme** [comment]
This does not just affect private modules, this would affect any scoped modules (public or private):
- https://docs.npmjs.com/misc/scope
- https://docs.npmjs.com/getting-started/scoped-packages

I believe the code here assumes that every sub-directory immediately within "node_modules" contains a package.json file, e.g. `./node_modules/other-package/package.json`

However, for scoped packages, the scope will be an intermediate level in the path structure, e.g. `./node_modules/@scope/other-package/package.json`

I would suggest either using [glob](https://www.npmjs.com/package/glob) to find all package.json files, or altering your directory traversal code to descend into directories that begin with "@" and treat them like node_modules directories.

**Comment by mwilliamson** [comment]
Thanks -- having special handling for directories that begin with `@` sounds sensible to me.

Recursing through `node_modules` to find packages might not be the best approach way to find dependencies though -- alternatives are:

* reading `dependencies` (and possibly `devDependencies`) in `package.json`.
* parsing calls to `require()`.
* hooking into browserify somehow. This would actually be the most useful for how I use this module: recursing through `node_modules` probably pulls in too many modules, while the other two alternatives above might pull in too few.
