### ISSUE TITLE
Deduplicate licenses

### ISSUE THREAD

**Issue by FGRibreau** [mwilliamson/node-license-sniffer#6]
Hello !

Just discovered your tool, it's perfect for my use-case (thanks !) however I have a lot of duplicate licenses. E.g. from " Copyright (c) Isaac Z. Schlueter and Contributors" or "Copyright (c) Sindre Sorhus sindresorhus@gmail.com (sindresorhus.com)" would it be possible to have an option that group them?

**Comment by mwilliamson** [comment]
Hello, and thanks for the kind words. I'd be open to a patch adding this feature if it has tests, but don't intend to do it myself.

**Comment by FGRibreau** [comment]
I'm sorry I exceptionally won't have the time for it, however you can check out the fork to see out how it was done :) https://github.com/FGRibreau/node-license-sniffer/commit/7fd031db12581f30ac5526dbf20549bf51714680#diff-42a8246934b2bcec50e70524693a7abfR27

Thanks again for this nice tool!
